import { SEOHead } from '../components/SEOHead'
const scripts = [
  {title:'Demo 1: The Research Pipeline',steps:['User submits: "Research the competitive landscape for governed agentic AI and produce a 2,000-word briefing."','Lee Prime receives goal, creates task graph: research → synthesis → formatting → delivery.','Scheduler wakes Agent Nova (Research). Brain Sentinel confirms device health OK.','Agent Nova queries sources, extracts data, checkpoints to Memory Lake every 5 minutes.','TaskBroker issues Baton to Agent Archive (Memory) with Nova\'s raw findings.','Agent Archive stores, deduplicates, and structures the research corpus.','TaskBroker issues Baton to Agent Forge (Engineering/Writing) with synthesis instructions.','Agent Forge produces final briefing. Shield Aegis validates no external calls required.','Lee Prime delivers formatted report with full ops log attached. Total time: 8 minutes.']},
  {title:'Demo 2: The Code Generation Workflow',steps:['User submits: "Build a REST API for user authentication with tests and documentation."','Lee Prime decomposes: schema design → implementation → test suite → docs → review.','Agent Forge wakes. Designs schema, writes implementation. All file writes are Tier 2 approved.','Checkpoint saved to Memory Lake after each module. Device thermal check passes.','Agent Forge passes Baton to test-specialized sub-agent. Tests written and run.','Failures logged to Memory Lake. Agent Forge wakes again to fix. Loop until green.','Documentation agent wakes, reads Memory Lake for context, produces README.','Shield Aegis final review: no unauthorized external calls, all files within scope.','Lee Prime delivers complete codebase with audit trail of every decision made.']},
  {title:'Demo 3: Enterprise Ops Governance Demo',steps:['Operator submits: "Process Q3 vendor invoices and flag anomalies for approval."','Lee Prime classifies: Tier 3 task (external data access). Routes approval request to operator.','Operator approves. Shield Aegis records authorization with timestamp and operator ID.','Agent Forge reads invoice data. Every read logged to ops trail.','Anomaly detection runs. Three invoices flagged. Break-glass? No — standard escalation.','Lee Prime generates anomaly report. Routes to operator dashboard.','Operator reviews, approves two, rejects one. All decisions logged with reasons.','Memory Lake stores full audit trail. Compliance report auto-generated.','Governance dashboard updated. All actions traceable end-to-end with zero ambiguity.']}
]
export default function DemoScripts() {
  return (<><SEOHead title="Demo Scripts" description="Agent Lee hero demo scripts — research pipeline, code generation, enterprise ops." /><div className="max-w-5xl mx-auto px-4 py-20"><div className="text-center mb-16"><div className="inline-block border border-cyan-800 rounded-full px-4 py-1 text-cyan-400 text-xs font-semibold tracking-widest uppercase mb-6">Demo Scripts</div><h1 className="text-4xl font-black text-white mb-4">Hero Demo Workflows</h1><p className="text-gray-400 text-lg max-w-2xl mx-auto">Three production-grade demos that show the governed execution lifecycle end-to-end.</p></div><div className="space-y-12">{scripts.map((s,i)=><div key={s.title} className="bg-gray-900 border border-gray-800 rounded-2xl p-8"><div className="text-cyan-400 font-black text-5xl opacity-20 mb-2">{i+1}</div><h2 className="text-2xl font-bold text-white mb-6">{s.title}</h2><ol className="space-y-3">{s.steps.map((step,j)=><li key={j} className="flex gap-4"><span className="shrink-0 w-6 h-6 rounded-full border border-cyan-800 text-cyan-400 text-xs flex items-center justify-center font-bold">{j+1}</span><p className="text-gray-300 text-sm leading-relaxed">{step}</p></li>)}</ol></div>)}</div></div></>)
}
